version: 2
definitions:
  build_defaults: &build_defaults
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10-browsers
jobs:
  checkout_code:
    <<: *build_defaults
    steps:
      - checkout
      - run:
          name: Version command
          command: echo "Running checkout"
  bundle_dependencies:
    <<: *build_defaults
    steps:
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
  lint:
    <<: *build_defaults
    steps:
      - run:
          name: Run Linter
          command: yarn lint
  test:
    <<: *build_defaults
    steps:
      - run:
          name: Runnimg Tests
          command: yarn test                           
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: latest
      - bundle_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: latest
      - lint:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: latest
      - test:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: latest                            