version: 2
definitions:
  build_defaults: &build_defaults
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10-browsers
  test_defaults: &test_defaults
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10-browsers
jobs:
  checkout_code:
    <<: *build_defaults
    steps:
      - checkout
      - run:
        name: Version command
        command: 
          echo "Running checkout"
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: latest